#!/bin/bash
# ==============================================================================
# Deployment Script for ForexTradingBot Application
#
# This script is executed on the target server by the GitHub Actions CI/CD pipeline.
# It handles pulling the latest configurations, managing Docker Compose services,
# and ensuring the application is deployed correctly.
#
# Environment Variables expected from GitHub Actions:
#   - SECRET_DB_PASSWORD
#   - SECRET_TELEGRAM_BOT_TOKEN
#   - SECRET_TELEGRAM_API_ID
#   - SECRET_TELEGRAM_API_HASH
#   - SECRET_LOG_MONITOR_TELEGRAM_CHANNEL_ID
#   - SECRET_CRYPTOPAY_API_TOKEN
#   - SECRET_CRYPTOPAY_API_KEY
#   - SECRET_CRYPTOPAY_WEBHOOK_SECRET
#   - GIT_BRANCH_NAME (current Git branch being deployed)
#   - DEPLOY_IMAGE_TAG (the Docker image tag to deploy, e.g., 'v1.2.3' or 'abcdef1')
# ==============================================================================

# --- Configuration and Safety Nets ---
set -euo pipefail # Exit on error, undefined variable, or pipe failure
# set -x # Uncomment for verbose script execution (debugging)

# --- Script Constants ---
readonly ENV_FILE_NAME=".env.production"
readonly DOCKER_COMPOSE_FILE_NAME="docker-compose.yml" # Or your specific compose file

# --- Logging Helper ---
log_info() {
  echo "INFO: $1"
}
log_warn() {
  echo "WARN: $1" >&2
}
log_error() {
  echo "ERROR: $1" >&2
  exit 1
}

# --- Pre-flight Checks ---
log_info "Performing pre-flight checks..."
check_command_exists() {
  if ! command -v "$1" &> /dev/null; then
    log_error "Command '$1' not found. Please install it and ensure it's in the PATH."
  fi
}
check_command_exists "git"
check_command_exists "docker"
check_command_exists "docker compose" # Checks for Docker Compose V2 plugin

# --- Validate Required Environment Variables ---
log_info "Validating required environment variables from CI..."
required_vars=(
  "SECRET_DB_PASSWORD" "SECRET_TELEGRAM_BOT_TOKEN" "SECRET_TELEGRAM_API_ID"
  "SECRET_TELEGRAM_API_HASH" "SECRET_LOG_MONITOR_TELEGRAM_CHANNEL_ID"
  "SECRET_CRYPTOPAY_API_TOKEN" "SECRET_CRYPTOPAY_API_KEY" "SECRET_CRYPTOPAY_WEBHOOK_SECRET"
  "GIT_BRANCH_NAME" "DEPLOY_IMAGE_TAG"
)
for var in "${required_vars[@]}"; do
  if [ -z "${!var:-}" ]; then # Check if the variable is unset or empty
    log_error "Required environment variable '$var' is not set. Deployment cannot proceed."
  fi
done
log_info "All required environment variables are set."
log_info "Deploying Git Branch: $GIT_BRANCH_NAME"
log_info "Deploying Docker Image Tag: $DEPLOY_IMAGE_TAG"


# --- Prepare .env.production File ---
# This file will store secrets and configurations for docker-compose.
# It's created if it doesn't exist, using secrets passed from GitHub Actions.
# For maximum security, this file should ideally be managed on the server
# using a secrets management tool, and this script would only ensure it's present.
log_info "Preparing '$ENV_FILE_NAME' file..."
if [ ! -f "$ENV_FILE_NAME" ]; then
  log_warn "'$ENV_FILE_NAME' not found. Creating it with secrets from environment variables."
  
  # Using a temporary file for atomic write if needed, but simple cat is often fine.
  # Ensure no sensitive data is accidentally logged if 'set -x' is enabled.
  (
    set +x # Temporarily disable verbose logging for this block
    cat > "$ENV_FILE_NAME" << EOL
# Auto-generated by deploy.sh if not present.
# Contains sensitive data and runtime configurations for docker-compose.

# --- Database Configuration ---
DB_HOST=db
DB_PORT=5432
DB_NAME=forextrading
DB_USER=forexuser
DB_PASSWORD=${SECRET_DB_PASSWORD}

# --- Telegram Configuration ---
TELEGRAM_BOT_TOKEN=${SECRET_TELEGRAM_BOT_TOKEN}
TELEGRAM_API_ID=${SECRET_TELEGRAM_API_ID}
TELEGRAM_API_HASH=${SECRET_TELEGRAM_API_HASH}
TELEGRAM_CHANNEL_ID=${SECRET_LOG_MONITOR_TELEGRAM_CHANNEL_ID} # For log_monitor

# --- Cryptopay Configuration ---
CRYPTOPAY_API_TOKEN=${SECRET_CRYPTOPAY_API_TOKEN}
CRYPTOPAY_API_KEY=${SECRET_CRYPTOPAY_API_KEY}
CRYPTOPAY_WEBHOOK_SECRET=${SECRET_CRYPTOPAY_WEBHOOK_SECRET}

# --- Docker Image Tags (used by docker-compose.yml) ---
# These should match the services defined in your docker-compose.yml
# And use the DEPLOY_IMAGE_TAG passed from CI.
REGISTRY_PREFIX="${REGISTRY:-ghcr.io}" # Use REGISTRY from CI or default
IMAGE_NAME_BASE="${IMAGE_NAME:-${GITHUB_REPOSITORY}}" # Use IMAGE_NAME from CI or default
APP_IMAGE_TAG=${DEPLOY_IMAGE_TAG} # Primary application image tag

# Example: If your docker-compose.yml references these specific variables for image tags
WEBAPI_IMAGE_TAG=${APP_IMAGE_TAG}
BACKGROUNDTASKS_IMAGE_TAG=${APP_IMAGE_TAG}
TELEGRAMPANEL_IMAGE_TAG=${APP_IMAGE_TAG}
# LOGMONITOR_IMAGE_TAG=${APP_IMAGE_TAG} # If log_monitor is built with the same tag

# --- Other Runtime Configurations (can also be directly in docker-compose.yml or Dockerfile ENV) ---
ASPNETCORE_ENVIRONMENT=Production
DOTNET_RUNNING_IN_CONTAINER=true
# Add other non-secret runtime configurations if managed via .env file
EOL
  )
  chmod 600 "$ENV_FILE_NAME" # Set restrictive permissions
  log_info "'$ENV_FILE_NAME' created successfully with restrictive permissions."
else
  log_info "'$ENV_FILE_NAME' already exists. It will be used by docker-compose."
  # Optional: Update specific image tags in the existing .env file if needed.
  # This requires more complex parsing (e.g., sed/awk) and is generally avoided
  # if the docker-compose.yml can directly use DEPLOY_IMAGE_TAG or if .env is regenerated.
  # For now, we assume docker-compose.yml is structured to use these.
  # Example update (use with caution):
  # sed -i "s/^WEBAPI_IMAGE_TAG=.*/WEBAPI_IMAGE_TAG=${DEPLOY_IMAGE_TAG}/" "$ENV_FILE_NAME"
fi

# --- Ensure docker-compose.yml is Present ---
if [ ! -f "$DOCKER_COMPOSE_FILE_NAME" ]; then
    log_error "Docker Compose file '$DOCKER_COMPOSE_FILE_NAME' not found. It should have been pulled by Git."
fi
log_info "Using Docker Compose file: $DOCKER_COMPOSE_FILE_NAME"

# --- Docker Compose Operations ---
# The docker-compose.yml should be structured to use environment variables from .env.production
# for image tags (e.g., image: ${REGISTRY_PREFIX}/${IMAGE_NAME_BASE}/webapi:${WEBAPI_IMAGE_TAG})
# and for any sensitive configurations if not using Docker Swarm secrets.

log_info "Pulling the specific Docker images defined in '$DOCKER_COMPOSE_FILE_NAME'..."
# Pass .env.production to ensure compose uses the correct image tags and configurations.
if ! docker compose --env-file "$ENV_FILE_NAME" -f "$DOCKER_COMPOSE_FILE_NAME" pull; then
  log_error "Failed to pull Docker images. Check image names, tags in '$ENV_FILE_NAME' and '$DOCKER_COMPOSE_FILE_NAME', and registry access."
fi
log_info "Docker images pulled successfully."

log_info "Stopping and removing existing Docker application containers..."
# Use --remove-orphans to clean up services no longer defined in the compose file.
if ! docker compose --env-file "$ENV_FILE_NAME" -f "$DOCKER_COMPOSE_FILE_NAME" down --remove-orphans --volumes; then
  log_warn "Failed to cleanly stop and remove all containers/volumes. Proceeding, but check for residuals."
fi
# '--volumes' will remove named volumes declared in the `volumes` section of the compose file
# and anonymous volumes attached to containers. Use with caution if you have persistent data
# in named volumes that should not be deleted on 'down'. For databases, data is usually
# in a host-mounted volume or a named volume specified with `external: true` or managed separately.

# If using Docker Swarm and Docker Secrets (this script assumes standalone Docker Compose by default)
# If in Swarm mode, secret management would be different (e.g., `docker secret create/rm`).
# This script is geared towards using .env files for secrets with standalone `docker compose`.

log_info "Starting Docker services using '$DOCKER_COMPOSE_FILE_NAME'..."
if ! docker compose --env-file "$ENV_FILE_NAME" -f "$DOCKER_COMPOSE_FILE_NAME" up -d --force-recreate --remove-orphans; then
  log_error "Failed to start Docker services. Check compose file, .env file, and Docker daemon logs."
fi
# --force-recreate ensures containers are recreated even if their configuration hasn't changed,
# which is useful if the image was updated with the same tag.

# --- Post-Deployment Health Checks and Logging ---
log_info "Waiting for services to stabilize (e.g., 30 seconds)..."
sleep 30

log_info "Current Docker container status:"
docker compose --env-file "$ENV_FILE_NAME" -f "$DOCKER_COMPOSE_FILE_NAME" ps

log_info "Displaying recent logs for all services (last 100 lines)..."
# Use --no-log-prefix for cleaner logs if preferred
docker compose --env-file "$ENV_FILE_NAME" -f "$DOCKER_COMPOSE_FILE_NAME" logs --tail 100 --timestamps

# Optional: Add specific health checks for critical services
# Example:
# log_info "Performing health check for WebAPI service..."
# WEBAPI_CONTAINER_NAME=$(docker compose --env-file "$ENV_FILE_NAME" -f "$DOCKER_COMPOSE_FILE_NAME" ps -q webapi)
# if [ -n "$WEBAPI_CONTAINER_NAME" ]; then
#   if docker inspect "$WEBAPI_CONTAINER_NAME" --format '{{.State.Health.Status}}' | grep -q "healthy"; then
#     log_info "WebAPI service is healthy."
#   elif docker inspect "$WEBAPI_CONTAINER_NAME" --format '{{.State.Status}}' | grep -q "running"; then
#     log_warn "WebAPI service is running but health status is not 'healthy' or not available. Check service logs."
#     docker compose --env-file "$ENV_FILE_NAME" -f "$DOCKER_COMPOSE_FILE_NAME" logs webapi --tail 50
#   else
#     log_error "WebAPI service is not running. Deployment may have failed."
#   fi
# else
#   log_error "WebAPI container not found. Deployment likely failed."
# fi

# --- Clean up old Docker images (optional) ---
# log_info "Cleaning up dangling Docker images..."
# docker image prune -af || log_warn "Failed to prune Docker images."

log_info "--- Deployment Script Finished Successfully ---"