#!/bin/bash
#
# deploy.sh: Handles application deployment on the target server.
# ... (کامنت‌های ابتدای اسکریپت مانند قبل) ...

# --- Strict Mode & Error Handling ---
set -euo pipefail
trap 'echo "ERROR: A command failed at line $LINENO. See output above for details." >&2; exit 1' ERR
trap 'echo "Deployment interrupted." >&2; exit 1' SIGINT SIGTERM

# --- Configuration & Constants ---
readonly ENV_FILE_PATH=".env.production"
# مسیر پلاگین Docker Compose که شما تایید کردید
readonly DOCKER_COMPOSE_PLUGIN_DIR="/usr/libexec/docker/cli-plugins"
readonly DOCKER_COMPOSE_PLUGIN_EXEC="${DOCKER_COMPOSE_PLUGIN_DIR}/docker-compose" # نام فایل اجرایی پلاگین

# --- Logging Functions ---
# ... (توابع لاگ بدون تغییر) ...
log_info() {
  echo "INFO: $1"
}
log_warn() {
  echo "WARNING: $1" >&2
}
log_error() {
  echo "ERROR: $1" >&2
  exit 1
}
log_success() {
  echo "SUCCESS: $1"
}
log_debug() {
  if [[ "${DEBUG_DEPLOY:-false}" == "true" ]]; then
    echo "DEBUG: $1"
  fi
}

# --- Helper Functions ---
# ... (check_env_var بدون تغییر) ...
check_env_var() {
  local var_name="$1"
  if [ -z "${!var_name:-}" ]; then
    log_error "Required environment variable '$var_name' is not set or is empty."
  fi
}

# متغیر سراسری برای دستور docker
DOCKER_CMD=""

check_commands_exist() {
    log_debug "Checking required commands..."
    log_debug "Initial PATH: $PATH"
    log_debug "User: $(whoami), Effective User: $(id -u -n)"

    # 1. به صراحت مسیر پلاگین Docker Compose را به PATH اضافه می‌کنیم
    if [ -d "$DOCKER_COMPOSE_PLUGIN_DIR" ]; then
        log_debug "Adding Docker Compose plugin directory to PATH: $DOCKER_COMPOSE_PLUGIN_DIR"
        export PATH="$DOCKER_COMPOSE_PLUGIN_DIR:$PATH"
        log_debug "Updated PATH: $PATH"
    else
        log_warn "Docker Compose plugin directory not found at $DOCKER_COMPOSE_PLUGIN_DIR. This might be an issue."
    fi

    # 2. پیدا کردن دستور git
    if ! command -v git &> /dev/null; then
        log_error "Git not found. Please install Git."
    fi
    log_debug "Git found: $(command -v git)"

    # 3. پیدا کردن دستور docker
    if command -v docker &> /dev/null; then
        DOCKER_CMD=$(command -v docker)
        log_debug "Docker found in PATH: $DOCKER_CMD"
    elif [ -x "/usr/bin/docker" ]; then
        DOCKER_CMD="/usr/bin/docker"
        log_debug "Docker found at /usr/bin/docker (fallback)"
    else
        log_error "Docker executable not found in PATH or /usr/bin/docker."
    fi

    # 4. تست کردن docker compose (به عنوان پلاگین docker)
    log_debug "Attempting to verify Docker Compose plugin with: '$DOCKER_CMD compose version'"
    if "$DOCKER_CMD" compose version &> /tmp/docker_compose_test_output; then
        log_debug "SUCCESS: '$DOCKER_CMD compose version' executed successfully. Output:"
        cat /tmp/docker_compose_test_output
    else
        log_warn "FAILURE: '$DOCKER_CMD compose version' failed. Output/Error:"
        cat /tmp/docker_compose_test_output >&2
        # تلاش برای اجرای مستقیم پلاگین به عنوان آخرین راه حل (بیشتر برای دیباگ)
        log_warn "Attempting to run plugin directly: '$DOCKER_COMPOSE_PLUGIN_EXEC version' (if it exists)"
        if [ -x "$DOCKER_COMPOSE_PLUGIN_EXEC" ]; then
             if "$DOCKER_COMPOSE_PLUGIN_EXEC" version &> /tmp/docker_compose_direct_output; then
                log_warn "Direct plugin execution '$DOCKER_COMPOSE_PLUGIN_EXEC version' succeeded. Output:"
                cat /tmp/docker_compose_direct_output
                log_warn "This indicates 'docker compose' (plugin invocation) is not working, but the plugin binary itself is executable."
             else
                log_warn "Direct plugin execution '$DOCKER_COMPOSE_PLUGIN_EXEC version' also failed. Output/Error:"
                cat /tmp/docker_compose_direct_output >&2
             fi
        else
            log_warn "Plugin executable not found or not executable at $DOCKER_COMPOSE_PLUGIN_EXEC"
        fi
        log_error "Docker Compose plugin (V2) is not working correctly even after attempting to modify PATH. Please check Docker installation and plugin setup for non-interactive sessions."
    fi
    
    log_info "All command checks passed."
}

# --- Main Deployment Logic ---
main() {
  # ... (بخش validate environment variables و لاگ‌های اولیه مانند قبل) ...
  log_info "--- Starting Deployment Script ---"
  log_debug "Script started. User: $(whoami), PATH: $PATH"
  check_env_var "GIT_BRANCH_NAME"
  # ... (سایر check_env_var ها)
  check_env_var "SECRET_TELEGRAM_CHANNEL_ID_FOR_LOG_MONITOR"

  log_info "Deployment Target Branch: $GIT_BRANCH_NAME"
  log_info "Deployment Docker Image: ${REGISTRY_GHCR}/${IMAGE_NAME_BASE}:${DEPLOY_IMAGE_TAG}"

  log_info ">>> Performing pre-flight checks..."
  check_commands_exist # DOCKER_CMD در اینجا تنظیم می‌شود

  # --- Prepare .env.production File ---
  # ... (بخش cat > "$ENV_FILE_PATH" << EOL مانند قبل، با اطمینان از صحت DB_HOST) ...
  log_info ">>> Preparing $ENV_FILE_PATH file..."
  cat > "$ENV_FILE_PATH" << EOL
# Auto-generated by deploy.sh
REGISTRY=${REGISTRY_GHCR}
GITHUB_REPOSITORY=${IMAGE_NAME_BASE}
IMAGE_TAG=${DEPLOY_IMAGE_TAG}
DB_HOST=db # یا 'forex-postgres' اگر نام سرویس در docker-compose.yml شما این است
DB_PORT=5432
DB_NAME=${DB_NAME_OVERRIDE:-forextrading}
DB_USER=${DB_USER_OVERRIDE:-forexuser}
DB_PASSWORD=${SECRET_POSTGRES_SERVICE_PASSWORD}
DB_CONNECTION_STRING_APP=${SECRET_DB_CONNECTION_STRING} # مطمئن شوید Host= در این رشته با DB_HOST بالا مطابقت دارد
TELEGRAM_BOT_TOKEN=${SECRET_TELEGRAM_BOT_TOKEN}
TELEGRAM_API_ID=${SECRET_TELEGRAM_API_ID}
TELEGRAM_API_HASH=${SECRET_TELEGRAM_API_HASH}
LOG_MONITOR_TELEGRAM_CHANNEL_ID=${SECRET_TELEGRAM_CHANNEL_ID_FOR_LOG_MONITOR}
$( [ -n "${SECRET_WTELEGRAMBOT:-}" ] && echo "WTELEGRAMBOT_ENV_VAR_NAME=${SECRET_WTELEGRAMBOT}" || echo "# SECRET_WTELEGRAMBOT not set or empty" )
EOL
  chmod 600 "$ENV_FILE_PATH"
  log_info "'$ENV_FILE_PATH' created/updated."

  # --- Update Source Code ---
  # ... (بخش git fetch و git reset مانند قبل) ...
  log_info ">>> Updating source code from Git branch: $GIT_BRANCH_NAME..."
  # ... (دستورات git) ...
  git reset --hard "origin/$GIT_BRANCH_NAME"
  log_success "Source code updated."

  # --- Docker Compose Operations ---
  # از DOCKER_CMD که پیدا شده استفاده می‌کنیم
  log_info ">>> Pulling Docker images..."
  "$DOCKER_CMD" compose --env-file "$ENV_FILE_PATH" pull

  log_info ">>> Stopping containers..."
  "$DOCKER_CMD" compose --env-file "$ENV_FILE_PATH" down --remove-orphans --timeout 60

  log_info ">>> Starting Docker services..."
  "$DOCKER_CMD" compose --env-file "$ENV_FILE_PATH" up -d --remove-orphans --force-recreate --renew-anon-volumes

  log_success "Docker services started."

  # --- Post-Deployment ---
  # ... (بخش sleep, ps, logs مانند قبل، با استفاده از DOCKER_CMD) ...
  log_info ">>> Waiting for services (30s)..."
  sleep 30
  log_info ">>> Container status:"
  "$DOCKER_CMD" compose --env-file "$ENV_FILE_PATH" ps
  log_info ">>> Recent logs:"
  "$DOCKER_CMD" compose --env-file "$ENV_FILE_PATH" logs --tail 100
  log_success "--- Deployment Script Finished ---"
}

# --- Execute Main Function ---
main "$@"