#!/bin/bash
# ==============================================================================
# Robust Deployment Script for ForexTradingBot Application
#
# Handles environment setup, Docker Compose orchestration, and basic health checks.
# Expected Environment Variables from CI:
#   SECRET_DB_PASSWORD, SECRET_TELEGRAM_BOT_TOKEN, ..., GIT_BRANCH_NAME,
#   DEPLOY_IMAGE_TAG, REGISTRY_GHCR, IMAGE_NAME_BASE
# ==============================================================================

# --- Strict Mode & Configuration ---
set -euo pipefail # Exit on error, undefined variable, or pipe failure
# set -x          # Uncomment for verbose debugging

readonly SCRIPT_NAME=$(basename "$0")
readonly ENV_FILE_NAME=".env.production"
readonly DOCKER_COMPOSE_FILE_NAME="docker-compose.yml" # Ensure this matches your compose file

# --- Logging Utilities ---
log_header() { echo -e "\n--- $1 ---"; }
log_info() { echo "INFO: [$SCRIPT_NAME] $1"; }
log_warn() { echo "WARN: [$SCRIPT_NAME] $1" >&2; }
log_error_exit() { echo "ERROR: [$SCRIPT_NAME] $1" >&2; exit 1; }

# --- Pre-flight Checks ---
log_header "Performing Pre-flight Checks"
check_command_exists() {
  command -v "$1" >/dev/null 2>&1 || log_error_exit "Required command '$1' is not installed or not in PATH."
}
check_command_exists "git"
check_command_exists "docker"
check_command_exists "docker compose"

# --- Validate Required Environment Variables ---
log_info "Validating required environment variables from CI..."
required_ci_vars=(
  "SECRET_DB_PASSWORD" "SECRET_TELEGRAM_BOT_TOKEN" "SECRET_TELEGRAM_API_ID"
  "SECRET_TELEGRAM_API_HASH" "SECRET_LOG_MONITOR_TELEGRAM_CHANNEL_ID"
  "SECRET_CRYPTOPAY_API_TOKEN" "SECRET_CRYPTOPAY_API_KEY" "SECRET_CRYPTOPAY_WEBHOOK_SECRET"
  "GIT_BRANCH_NAME" "DEPLOY_IMAGE_TAG" "REGISTRY_GHCR" "IMAGE_NAME_BASE"
)
for var in "${required_ci_vars[@]}"; do
  if [ -z "${!var:-}" ]; then
    log_error_exit "Required CI environment variable '$var' is not set."
  fi
done
log_info "All required CI environment variables are set."
log_info "Deploying Git Branch: $GIT_BRANCH_NAME, Docker Image Tag: $DEPLOY_IMAGE_TAG"

# --- Prepare .env.production File ---
log_header "Preparing '$ENV_FILE_NAME' File"
# This approach creates/overwrites the .env file with values from CI.
# For higher security, consider injecting secrets via a more secure mechanism if available
# or ensure this file is heavily restricted on the server.
log_info "Creating/Overwriting '$ENV_FILE_NAME' with current deployment configurations..."
(
  set +x # Avoid logging secrets if -x is on
  cat > "$ENV_FILE_NAME" << EOL
# Auto-generated by $SCRIPT_NAME during deployment.
# Contains sensitive data and runtime configurations for docker-compose.

# --- Database Configuration ---
DB_HOST=db
DB_PORT=5432
DB_NAME=forextrading
DB_USER=forexuser
DB_PASSWORD=${SECRET_DB_PASSWORD}

# --- Telegram Configuration ---
TELEGRAM_BOT_TOKEN=${SECRET_TELEGRAM_BOT_TOKEN}
TELEGRAM_API_ID=${SECRET_TELEGRAM_API_ID}
TELEGRAM_API_HASH=${SECRET_TELEGRAM_API_HASH}
TELEGRAM_CHANNEL_ID=${SECRET_LOG_MONITOR_TELEGRAM_CHANNEL_ID}

# --- Cryptopay Configuration ---
CRYPTOPAY_API_TOKEN=${SECRET_CRYPTOPAY_API_TOKEN}
CRYPTOPAY_API_KEY=${SECRET_CRYPTOPAY_API_KEY}
CRYPTOPAY_WEBHOOK_SECRET=${SECRET_CRYPTOPAY_WEBHOOK_SECRET}

# --- Docker Image Tags (to be used in docker-compose.yml) ---
# These variables will be substituted into your docker-compose.yml
REGISTRY_PREFIX=${REGISTRY_GHCR}
IMAGE_REPO=${IMAGE_NAME_BASE} # e.g., yourusername/forextradingbot
APP_PRIMARY_TAG=${DEPLOY_IMAGE_TAG}

# Example: If docker-compose.yml uses these specific variables for each service
# Ensure these variable names match what's used in your docker-compose.yml for image definitions
WEBAPI_IMAGE_TAG=${APP_PRIMARY_TAG}
BACKGROUNDTASKS_IMAGE_TAG=${APP_PRIMARY_TAG}
TELEGRAMPANEL_IMAGE_TAG=${APP_PRIMARY_TAG}
# LOGMONITOR_IMAGE_TAG=${APP_PRIMARY_TAG} # If applicable

# --- Other Runtime Configurations ---
ASPNETCORE_ENVIRONMENT=Production
DOTNET_RUNNING_IN_CONTAINER=true
# Add other non-secret runtime configurations here if they are managed via this .env file
# Alternatively, they can be set directly in the docker-compose.yml or Dockerfile ENV.
EOL
)
chmod 600 "$ENV_FILE_NAME" # Restrict permissions
log_info "'$ENV_FILE_NAME' has been configured."

# --- Ensure Docker Compose File Exists ---
if [ ! -f "$DOCKER_COMPOSE_FILE_NAME" ]; then
    log_error_exit "Docker Compose file '$DOCKER_COMPOSE_FILE_NAME' not found. It should be part of the Git repository."
fi
log_info "Using Docker Compose file: $DOCKER_COMPOSE_FILE_NAME"

# --- Docker Compose Operations ---
# The docker-compose.yml MUST use variable substitution for image tags, e.g.:
# services:
#   webapi:
#     image: \${REGISTRY_PREFIX}/\${IMAGE_REPO}:\${WEBAPI_IMAGE_TAG}

log_header "Performing Docker Compose Operations"

log_info "Pulling Docker images specified in '$DOCKER_COMPOSE_FILE_NAME' (using tags from '$ENV_FILE_NAME')..."
# Docker Compose will use variables from .env.production (and .env if present) by default
# or explicitly with --env-file
if ! docker compose -f "$DOCKER_COMPOSE_FILE_NAME" --env-file "$ENV_FILE_NAME" pull; then
  log_error_exit "Failed to pull Docker images. Check image names, tags, registry access, and Docker daemon status."
fi
log_info "Docker images pulled successfully."

log_info "Stopping and removing existing application containers (if any)..."
# --remove-orphans cleans up services no longer in the compose file.
# Omitting --volumes by default to protect persistent data. Add if intended.
if ! docker compose -f "$DOCKER_COMPOSE_FILE_NAME" --env-file "$ENV_FILE_NAME" down --remove-orphans; then
  log_warn "Could not cleanly stop all services. Proceeding, but manual cleanup might be needed."
fi

log_info "Starting application services using '$DOCKER_COMPOSE_FILE_NAME'..."
# --force-recreate ensures containers are recreated using the newly pulled images.
# -d runs in detached mode.
if ! docker compose -f "$DOCKER_COMPOSE_FILE_NAME" --env-file "$ENV_FILE_NAME" up -d --force-recreate --remove-orphans --timeout 60; then
  log_error_exit "Failed to start Docker services. Check compose file, .env file, service logs, and Docker daemon."
fi
log_info "Application services started."

# --- Post-Deployment Verification & Logging ---
log_header "Post-Deployment Verification"

log_info "Waiting for services to stabilize (e.g., 30-60 seconds)..."
sleep 45 # Adjust as needed based on service startup times

log_info "Current Docker container status:"
docker compose -f "$DOCKER_COMPOSE_FILE_NAME" --env-file "$ENV_FILE_NAME" ps

log_info "Displaying recent logs for all services (last 100 lines with timestamps)..."
docker compose -f "$DOCKER_COMPOSE_FILE_NAME" --env-file "$ENV_FILE_NAME" logs --tail 100 --timestamps

# Optional: Specific health check for a key service
# SERVICE_TO_CHECK="webapi" # Example
# log_info "Performing health check for '$SERVICE_TO_CHECK' service..."
# CONTAINER_ID=$(docker compose -f "$DOCKER_COMPOSE_FILE_NAME" --env-file "$ENV_FILE_NAME" ps -q "$SERVICE_TO_CHECK")
#
# if [ -n "$CONTAINER_ID" ]; then
#   HEALTH_STATUS=$(docker inspect "$CONTAINER_ID" --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}')
#   log_info "'$SERVICE_TO_CHECK' container ($CONTAINER_ID) status: $HEALTH_STATUS"
#   if [[ "$HEALTH_STATUS" == "healthy" || "$HEALTH_STATUS" == "running" ]]; then # "running" if no healthcheck defined
#     log_info "'$SERVICE_TO_CHECK' service appears to be operational."
#   else
#     log_warn "'$SERVICE_TO_CHECK' service status is '$HEALTH_STATUS'. Check logs for issues:"
#     docker compose -f "$DOCKER_COMPOSE_FILE_NAME" --env-file "$ENV_FILE_NAME" logs "$SERVICE_TO_CHECK" --tail 50
#   fi
# else
#   log_warn "'$SERVICE_TO_CHECK' container not found. Deployment might have issues."
# fi

# --- Optional: Clean up old/unused Docker images ---
# log_info "Cleaning up unused Docker images (dangling and older versions)..."
# docker image prune -af || log_warn "Failed to prune Docker images. This is non-critical."

log_header "Deployment Script Finished Successfully"
exit 0