version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=forextrading;Username=postgres;Password=re110121
      - TelegramBot__Token=7101564106:AAHbHL5hhGJK7aIKH7RGEX2ZG4nGvMHOmIE
      - TELEGRAM_SESSION_PATH=/app/telegram-sessions
    volumes:
      - ../telegram-sessions:/app/telegram-sessions
      - ../data-protection:/app/data-protection
    depends_on:
      - db
      - redis
    networks:
      - forex-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=forextrading
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=re110121
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - forex-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - forex-network

  backgroundtasks:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=forextrading;Username=postgres;Password=re110121
      - TelegramBot__Token=7101564106:AAHbHL5hhGJK7aIKH7RGEX2ZG4nGvMHOmIE
      - TELEGRAM_SESSION_PATH=/app/telegram-sessions
    volumes:
      - ../telegram-sessions:/app/telegram-sessions
      - ../data-protection:/app/data-protection
    depends_on:
      - db
      - redis
    networks:
      - forex-network
    command: dotnet BackgroundTasks.dll

networks:
  forex-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  telegram-sessions:
    driver: local 