version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=forextrading;Username=postgres;Password=your_password
      - TelegramBot__Token=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_SESSION_PATH=/app/telegram-sessions
    volumes:
      - telegram-sessions:/app/telegram-sessions
    depends_on:
      - db
    networks:
      - forex-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=forextrading
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=your_password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - forex-network

  hangfire:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - forex-network

networks:
  forex-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
  telegram-sessions:
    driver: local 