version: '3.8'

services:
  webapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=5432;Database=myappdb;User Id=postgres;Password=re110121;
      - Hangfire__ConnectionString=Server=localhost;Port=5432;Database=myappdb;User Id=postgres;Password=re110121;
    ports:
      - "5000:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  backgroundtasks:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=localhost;Port=5432;Database=myappdb;User Id=postgres;Password=re110121;
      - Hangfire__ConnectionString=Server=localhost;Port=5432;Database=myappdb;User Id=postgres;Password=re110121;
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=re110121
      - POSTGRES_DB=myappdb 